# Generated by Django 5.1.3 on 2024-11-19 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='active',
            new_name='activo',
        ),
    ]
